proxy:
  title: "Swan-Canning Riverpark: Data Dashboard"
  logo-url: file:///var/www/html/swan.png
  landing-page: /
  favicon-path: /var/www/html/swan.ico
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
# authentication: simple
  authentication: none
# admin-groups: admins
# # Example: 'simple' authentication configuration
# users:
# - name: admin
#   password: password
#   groups: admins
# - name: user
#   password: password
#   groups: users
# # Docker configuration
  docker:
#   internal-networking: true
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
# - id: 01_hello
#   display-name: Hello Shiny App
#   description: A simple reactive histogram
#   container-cmd: ["R", "-e", "shiny::runApp('/home/app')"]
#   container-image: registry.gitlab.com/analythium/shinyproxy-hello/hello:latest
#   logo-url: https://github.com/analythium/shinyproxy-1-click/raw/master/digitalocean/images/app-hist.png
#   access-groups: [admins, users]
# - id: 02_hello
#   display-name: Demo Shiny App
#   description: App with sliders and file upload
#   container-cmd: ["R", "-e", "shiny::runApp('/home/app')"]
#   container-image: analythium/shinyproxy-demo:latest
#   logo-url: https://github.com/analythium/shinyproxy-1-click/raw/master/digitalocean/images/app-dots.png
#   access-groups: [admins]
# - id: 03_giles
#   display-name: SCEVO Dash
#   description: Original SCEVO dashboard
#   container-cmd: ["R", "-e", "shiny::runApp('/home/app')"]
#   container-image: scevo-dashboard
#   logo-url: http://146.118.67.118/aed.png
#   access-groups: [admins]
  - id: scevo
    display-name: "SCEVO: Eyes on the River"
    description: "Data Dashboard for the Environmental condition of the Swan-Canning Estuary (Western Australia). Built as part of the Swan-Canning Estuary Virtual Observatory (SCEVO)"
    container-cmd: ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0');library(scevo);scevo::run_app()"]
    container-image: scevo
    logo-url: file:///var/www/html/scevo.png
#   access-groups: [admins]

logging:
  file:
    name: shinyproxy.log
